# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(choices=[('N', 'Neuro'), ('C', 'Cardio'), ('T', 'Trauma'), ('E', 'ENT'), ('GS', 'General Surgery'), ('M', 'Maternity'), ('O', 'Oncology'), ('U', 'Urology')], max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Doctor', 'Dr.')], max_length=6)),
                ('first_initial', models.CharField(max_length=4)),
                ('last_name', models.CharField(max_length=30)),
                ('occupied', models.BooleanField(default=False)),
                ('time_finish_shift', models.TimeField(verbose_name='Time finished shift')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('doctor', 'Dr.'), ('mr', 'Mr.'), ('mrs', 'Mrs.'), ('miss', 'Miss')], max_length=6)),
                ('first_initial', models.CharField(max_length=4)),
                ('last_name', models.CharField(max_length=30)),
                ('occupied', models.BooleanField(default=False)),
                ('time_finish_shift', models.TimeField(verbose_name='Time finished shift')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('being_seen', models.BooleanField(default=False)),
                ('injury_description', models.CharField(max_length=400)),
                ('allergies', models.CharField(max_length=150)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Department')),
            ],
        ),
    ]
