# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='priority',
            field=models.CharField(choices=[('1', 'Critical'), ('2', 'Serious'), ('3', 'Minor')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
