# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170820_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='being_seen',
        ),
        migrations.AddField(
            model_name='patient',
            name='room_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='title',
            field=models.CharField(choices=[('Doctor', 'Dr.'), ('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Miss', 'Miss')], max_length=6),
        ),
    ]
